$(CACHE_PATH)/bank.v
$(CACHE_PATH)/DRAMReal.v
$(CACHE_PATH)/memv.v
$(CACHE_PATH)/memc.v
$(CACHE_PATH)/cache.v
$(CACHE_PATH)/mem_system.v
$(HDL_PATH)/dff.v
$(HDL_PATH)/decode.sv
$(HDL_PATH)/execute.sv
$(HDL_PATH)/fetch.sv
$(HDL_PATH)/memory.sv
$(HDL_PATH)/write_back.sv
$(HDL_PATH)/pipeline.sv
$(HDL_PATH)/register_file.sv
$(HDL_PATH)/proc.sv
$(HDL_PATH)/core.sv
$(HDL_PATH)/DRAMIdeal.v
$(HDL_PATH)/DRAMStall.v
../riscv_reg_comp_if.sv

